config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :posts do
    resources :sections
  end

  devise_for :users

  root to: "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :sections, inverse_of: :post
end

app/models/section.rb
class Section < ActiveRecord::Base

  belongs_to :post, touch: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    postparams = post_params
    postparams[:user_id] = current_user.id

    @post = Post.new(postparams)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :short_description, :user_id)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_filter :load_post
  before_filter :load_section, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  def new
    @section = @post.sections.build
  end

  def create
    sectionparams = section_params
    sectionparams[:user_id] = current_user.id

    @section = @post.sections.build(sectionparams)

    respond_to do |format|
      if @section.save
        format.html { redirect_to [@post, @section], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

  def load_post
    @post = Post.find(params[:post_id])
  end

  def load_section
    @section = Section.find(params[:id])
  end

  def section_params
    section_params = params.require(:section).permit(:title, :description, :position, :user_id)
    section_params.update(params.permit(:post_id))
    section_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.slim
h1
  | Home#index
p
  | Find me in app/views/home/index.html.erb

app/views/layouts/application.html.slim
doctype html
html
  head
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    meta name="author"
    meta name="content"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    link rel="search" type="application/opensearchdescription+xml" title="Knome" href="/search.xml"

    == stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render "shared/header"
    .container
      = yield
      p.notice = notice
      p.alert = alert

app/views/posts/_form.html.slim
.row
  .col-md-8
    = simple_form_for(@post, html: { class: 'form-vertical' }) do |f|
      = render "shared/errors", model: @post
      = f.input :title
      = f.input :short_description
      .actions
        = f.button :submit

app/views/posts/edit.html.slim
h1
  | Editing Post
= render 'form'
= link_to 'Show', @post
|  | 
= link_to 'Back', posts_path

app/views/posts/index.html.slim
p#notice
  = notice


.row
  - @posts.each do |post|
    .col-md-4.img-portfolio
      a href="portfolio-item.html"
        img.img-responsive.img-hover alt="" src=""
      h3
        = post.title
      p = post.short_description
      div.actions
        = link_to 'Show', post
        '
        = link_to 'Edit', edit_post_path(post)
        '
        = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/new.html.slim
h1
  | New Post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice
  = notice
h1
  = @post.title
h4
  = @post.short_description
h3
  | Sections
  - @post.sections.each do |section|
    h3 Title
    = section.title
    h3 Description
    = section.description

= link_to 'Add Section', new_post_section_path(@post)
= " | "
= link_to 'Edit', edit_post_path(@post)
= " | "
= link_to 'Back', posts_path

app/views/sections/_form.html.slim
.row
  .col-md-8
    = simple_form_for([@post, @section], html: { class: 'form-vertical' }) do |f|
      = render "shared/errors", model: @post
      = f.input :title
      = f.input :description
      .actions
        = f.button :submit, 'Create'

app/views/sections/new.html.slim
h1
  | New Section
= render 'form'
= link_to 'Back', posts_path

app/views/sections/show.html.slim
p#notice
  = notice
h1
  = @section.title
h4
  = @section.description

= link_to 'Edit', edit_post_section_path(@post, id: @section)
= " | "
= link_to 'Back', post_path(@post)

app/views/shared/_errors.html.slim
- if model.errors.any?
  #error_explanation
    h2
      = pluralize(model.errors.count, "error")
      |  prohibited this post from being saved:
    ul
      - model.errors.full_messages.each do |message|
        li
          = message

app/views/shared/_header.html.slim
/! Navigation
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"  Polaris
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          a href="/posts/new"  New Post
        - if user_signed_in?
          li
            = link_to "Log out", destroy_user_session_path, method: :delete
        - else
          li
            = link_to "Sign in", new_user_session_path